### ISSUE TITLE
Parallel Testing Multiple Browsers

### ISSUE THREAD

**Issue by abhidp** [igniteram/testng-cucumber#3]
You are taking the browser from the config file where only one browser can be specified.
Can this also be run for tests in parallel for multiple browsers ? For this we need to parameterise TestNG.xml
Will it work after parameterization of testng.xml?

**Comment by igniteram** [comment]
@abhimassive Sorry for the late reply , it should work after parametrising testng.xml , you can create multiple instances of browser. If you have already figured it out , you could send a PR to this repo as it could be useful to others :)

closing this issue for now as this is a support issue and not an issue with this framework, please raise a new one if got any more issues!
